//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_2_2_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Helpers;
    using System.Xml.Linq;

    public partial class Employee
    {
        public int ID { get; set; }
        [Required ]
        [StringLength(12)]
        public string First_Name { get; set; }
        [Required]
        [StringLength(12)]
        public string Last_Name { get; set; }
        [Required (ErrorMessage ="invalid")]
        public string E_mail { get; set; }
        [Required (ErrorMessage ="its not Jordan number ")]
        [RegularExpression(@"^[0][789]{1} [0-9]{7}$")]
        public string Phone_Number { get; set; }
        [Required]
        [Range(18, 50)]
        public int Age { get; set; }
        [Required(ErrorMessage ="max length 10 character")]
        [StringLength(12)]
        public string Jop_Title { get; set; }
        public bool Gender { get; set; }



    }
}
