//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task3_5_2_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task3
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Phon { get; set; }
        public Nullable<int> Age { get; set; }
        public string Jop_Title { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Image { get; set; }
        public string CV { get; set; }
    }
}
