//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_13_2_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Majour
    {
        public int MajourID { get; set; }
        public string MajourName { get; set; }
        public int FactoryID { get; set; }
    
        public virtual Factory Factory { get; set; }
    }
}
